### ISSUE TITLE
LipSync

### ISSUE THREAD

**Issue by inshanrxxx1** [AnimaVR/NeuroSync_Local_API#1]
Hi, I ran the project, successfully generating frame data and csv file .I selected the Face Subj in unreal engine and am hearing audio playing but I'm not seeing any facial animations.

**Comment by AnimaVR** [comment]
Make sure it shows up in LiveLink list in Unreal and also in your metahumans FaceAnim_BP as well as the Metahuman itself.

![Screenshot 2024-11-17 222334](https://github.com/user-attachments/assets/16fa2fad-b2e9-4188-a6e1-4a8774f06cd4)
![Screenshot 2024-11-17 222345](https://github.com/user-attachments/assets/34bb7a90-e6d7-434f-a54c-e483d98ac737)
![Screenshot 2024-11-17 222351](https://github.com/user-attachments/assets/7319398c-7751-48a4-b0d9-3a6df3e97b9a)

**Comment by inshanrxxx1** [comment]
> Make sure it shows up in LiveLink list in Unreal and also in your metahumans FaceAnim_BP as well as the Metahuman itself.
> 
> ![Screenshot 2024-11-17 222334](https://private-user-images.githubusercontent.com/22724774/387010353-16fa2fad-b2e9-4188-a6e1-4a8774f06cd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4ODI2NzEsIm5iZiI6MTczMTg4MjM3MSwicGF0aCI6Ii8yMjcyNDc3NC8zODcwMTAzNTMtMTZmYTJmYWQtYjJlOS00MTg4LWE2ZTEtNGE4Nzc0ZjA2Y2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDIyMjYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMTg0MGNkZWQ3YWM2Y2Q2NDgwMTY2YjA0OTU5ZDA3YTU0NjE2OGMyZTM5NWZiODIxNGFhYjdjY2E1YzY1ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TT-qDc_H0ahe_xEIYuToequ8a0kXVTey1Uv9IBjsDbs) ![Screenshot 2024-11-17 222345](https://private-user-images.githubusercontent.com/22724774/387010355-34bb7a90-e6d7-434f-a54c-e483d98ac737.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4ODI2NzEsIm5iZiI6MTczMTg4MjM3MSwicGF0aCI6Ii8yMjcyNDc3NC8zODcwMTAzNTUtMzRiYjdhOTAtZTZkNy00MzRmLWE1NGMtZTQ4M2Q5OGFjNzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDIyMjYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMGU5MjFlOTQ2MTM5NTBjYzdlNzgzYTk4OTY1ZTUzYzliYTA5NGQyNWM4M2ZhMGZkMGMzMDk0Y2M1MGVlMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JBOnsk7UJyx89QLbDZYGgw_Qq0sTUYyG-Bdp5brcagY) ![Screenshot 2024-11-17 222351](https://private-user-images.githubusercontent.com/22724774/387010357-7319398c-7751-48a4-b0d9-3a6df3e97b9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4ODI2NzEsIm5iZiI6MTczMTg4MjM3MSwicGF0aCI6Ii8yMjcyNDc3NC8zODcwMTAzNTctNzMxOTM5OGMtNzc1MS00OGE0LWIwZDktM2E2ZGYzZTk3YjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDIyMjYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MThhYzM1ZDEyNDAwM2M3ZDkzYTUyZWZhZTg0ZmRjN2FmODg1MjAwMjFmMGMzMDlhYmNlYmYwZjFlNWE5NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tiGTHEIMRvhr_DeBUs3PMsTYfjDPCeyeTh4Gf4MLFV0)
> 
> play_generated_files.py streams a default animation on port 11111 so just open that and unreal and it should work if livelink is enabled like the above images.

Hi I was using a custom face bp which was the problem. Thanks for your assistance
